/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', '"Be Vietnam Pro"', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', '"Be Vietnam Pro"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'Consolas', 'monospace'],
        vietnamese: ['"Be Vietnam Pro"', '"Inter"', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
        glass: {
          light: 'rgba(255, 255, 255, 0.1)',
          medium: 'rgba(255, 255, 255, 0.2)',
          dark: 'rgba(255, 255, 255, 0.05)',
        },
        'accent-color': '#34d399',
        text: {
          primary: '#f9fafb',
          secondary: '#d1d5db',
          accent: '#34d399',
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'glass-shimmer': 'glassShimmer 2s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        glassShimmer: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#f3f4f6',
            lineHeight: '1.7',
            fontFamily: '"Inter", "Be Vietnam Pro", system-ui, sans-serif',
            fontSize: '1.125rem',
            p: {
              marginTop: '1.5em',
              marginBottom: '1.5em',
              fontFeatureSettings: '"kern", "liga", "clig", "calt"',
            },
            h1: {
              color: '#f3f4f6',
              fontFamily: '"Space Grotesk", "Be Vietnam Pro", system-ui, sans-serif',
              fontWeight: '700',
              fontSize: '2.5em',
              marginTop: '0',
              marginBottom: '0.8em',
              lineHeight: '1.1',
              letterSpacing: '-0.025em',
              fontFeatureSettings: '"cv02", "cv03", "cv04", "cv11"',
            },
            h2: {
              color: '#f3f4f6',
              fontFamily: '"Space Grotesk", "Be Vietnam Pro", system-ui, sans-serif',
              fontWeight: '600',
              fontSize: '1.875em',
              marginTop: '2em',
              marginBottom: '1em',
              lineHeight: '1.2',
              letterSpacing: '-0.02em',
              fontFeatureSettings: '"cv02", "cv03", "cv04", "cv11"',
            },
            h3: {
              color: '#f3f4f6',
              fontFamily: '"Space Grotesk", "Be Vietnam Pro", system-ui, sans-serif',
              fontWeight: '600',
              fontSize: '1.5em',
              marginTop: '1.6em',
              marginBottom: '0.6em',
              lineHeight: '1.25',
              letterSpacing: '-0.015em',
              fontFeatureSettings: '"cv02", "cv03", "cv04", "cv11"',
            },
            h4: {
              color: '#f3f4f6',
              fontFamily: '"Space Grotesk", "Be Vietnam Pro", system-ui, sans-serif',
              fontWeight: '600',
              fontSize: '1.25em',
              marginTop: '1.5em',
              marginBottom: '0.5em',
              lineHeight: '1.3',
              letterSpacing: '-0.01em',
            },
            strong: {
              color: '#f3f4f6',
              fontWeight: '600',
            },
            blockquote: {
              fontWeight: '500',
              fontStyle: 'italic',
              color: '#a1a1aa',
              borderLeftWidth: '0.25rem',
              borderLeftColor: '#34d399',
              quotes: '"\\201C""\\201D""\\2018""\\2019"',
              marginTop: '2em',
              marginBottom: '2em',
              paddingLeft: '1.5em',
              fontSize: '1.125em',
              lineHeight: '1.6',
            },
            code: {
              color: '#34d399',
              fontFamily: '"JetBrains Mono", "Fira Code", Consolas, monospace',
              fontWeight: '500',
              fontSize: '0.875em',
              fontFeatureSettings: '"calt", "liga"',
              backgroundColor: 'rgba(52, 211, 153, 0.1)',
              padding: '0.25em 0.375em',
              borderRadius: '0.25rem',
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              backgroundColor: 'rgba(15, 23, 42, 0.8)',
              color: '#f3f4f6',
              overflow: 'auto',
              fontSize: '0.875em',
              lineHeight: '1.7',
              marginTop: '2em',
              marginBottom: '2em',
              borderRadius: '0.75rem',
              padding: '1.5em',
              border: '1px solid rgba(255, 255, 255, 0.1)',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              fontSize: 'inherit',
              fontWeight: 'inherit',
              padding: '0',
              borderRadius: '0',
            },
            a: {
              color: '#34d399',
              textDecoration: 'underline',
              fontWeight: '500',
              textDecorationThickness: '2px',
              textUnderlineOffset: '3px',
              transition: 'all 0.2s ease',
            },
            'a:hover': {
              color: '#22c55e',
              textDecorationColor: '#22c55e',
            },
            ul: {
              listStyleType: 'none',
              paddingLeft: '0',
            },
            'ul > li': {
              position: 'relative',
              paddingLeft: '1.75em',
            },
            'ul > li::before': {
              content: '"•"',
              position: 'absolute',
              left: '0',
              color: '#34d399',
              fontWeight: 'bold',
            },
            ol: {
              paddingLeft: '1.75em',
            },
            'ol > li': {
              paddingLeft: '0.25em',
            },
            'ol > li::marker': {
              color: '#34d399',
              fontWeight: '600',
            },
          },
        },
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '112': '28rem',
        '128': '32rem',
      },
      screens: {
        'xs': '475px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
  ],
};
